# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 527c4b9bae1678975acf7efe8d52323749a4ac0a1bf5088b150903e50f9d8b9fe6d9e2eb65ac890aedd180ea95a8f8b060adf33e0e043262af18ac9e6abb35dd

test:
  secret_key_base: f05c75e87066f6817495362a1fdf102892333740fd42d5f1dca255710cc1bcbdadf89ab77cad3e928ed60b663bd0f8a82c47e1d185a1e861a733a33d344ca2ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
